import { StyleSheet } from 'react-native';

export const mainAppStyles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandBlock: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  kicker: { fontSize: 10, fontWeight: '900', letterSpacing: 1.8, marginBottom: 2 },
  title: { fontSize: 18, fontWeight: '800' },
  subtitle: { fontSize: 12, marginTop: 2 },
  badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  badgeText: { fontSize: 12, fontWeight: '800' },
  qrAction: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  qrActionText: { fontSize: 12, fontWeight: '800', letterSpacing: 0.8 },
  logoShell: {
    borderWidth: 1,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  logoHalo: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 18,
    transform: [{ rotate: '12deg' }],
  },
  logoCore: {
    width: '72%',
    height: '72%',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
  },
  logoBars: { flexDirection: 'row', alignItems: 'flex-end', gap: 3 },
  logoBar: { width: 4, borderRadius: 99 },
  logoBarThin: { width: 2, borderRadius: 99, opacity: 0.9 },
  content: { flex: 1 },
  screen: { flex: 1, width: '100%', maxWidth: '100%', padding: 12, gap: 10, overflow: 'hidden' },
  screenLocked: { overflow: 'hidden' },
  tabViewport: { flex: 1, width: '100%', maxWidth: '100%', overflow: 'hidden' },
  settingsContent: { width: '100%', paddingBottom: 24, overflow: 'hidden' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  cameraContainer: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  camera: { flex: 1, borderWidth: 1, borderRadius: 16, overflow: 'hidden' },
  cameraCompact: { minHeight: 260 },
  cameraOverlayActions: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    gap: 8,
  },
  cameraAction: {
    width: 38,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowButtons: { flexDirection: 'row', gap: 8, marginTop: 8, flexWrap: 'wrap' },
  btn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: 'transparent' },
  btnContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  btnText: { color: '#fff', fontWeight: '700' },
  smallBtn: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  actionBtn: { minWidth: 104 },
  smallActionBtn: { minWidth: 0, paddingHorizontal: 10, paddingVertical: 10 },
  scanPrimaryBtn: { minWidth: 0, alignSelf: 'flex-start' },
  scanFallbackCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginTop: 8,
    gap: 8,
  },
  scanFallbackTitle: { fontSize: 15, fontWeight: '800' },
  scanFallbackText: { fontSize: 13, lineHeight: 18 },
  inlineAction: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  compactAction: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  input: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 10, marginTop: 10 },
  pasteInput: { minHeight: 110 },
  backupInput: { minHeight: 180 },
  card: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 10, width: '100%', maxWidth: '100%', overflow: 'hidden' },
  cardContained: {
    overflow: 'hidden',
  },
  captureCard: {
    width: 180,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 6,
  },
  captureThumb: {
    width: '100%',
    height: 110,
    borderRadius: 10,
    backgroundColor: '#111',
  },
  captureMeta: { fontSize: 12, fontWeight: '800' },
  captureSubmeta: { fontSize: 11, fontWeight: '600' },
  captureText: { fontSize: 11, lineHeight: 15 },
  filterRow: { flexDirection: 'row', gap: 8, marginBottom: 4, marginTop: 10, flexWrap: 'wrap', width: '100%', maxWidth: '100%' },
  filterBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, width: '100%', maxWidth: '100%', overflow: 'hidden' },
  filterPrimaryRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flex: 1, minWidth: 0, overflow: 'hidden' },
  filterChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, flexShrink: 1, minWidth: 0 },
  filterChipCompact: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 14, flexShrink: 1, minWidth: 0 },
  filterChipNoGrow: { flexGrow: 0 },
  listContent: { paddingBottom: 18, width: '100%' },
  historyItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  code: { fontSize: 16, fontWeight: '800' },
  sectionTitle: { fontSize: 14, fontWeight: '700' },
  footer: { borderTopWidth: 1, paddingHorizontal: 8, paddingVertical: 8, flexDirection: 'row' },
  footerBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8 },
  footerAddBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 16,
    borderWidth: 1,
  },
  footerBtnInner: { alignItems: 'center', justifyContent: 'center', gap: 5 },
  selectionFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
  },
  selectionBtn: {
    padding: 8,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
  },
  modalView: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  qrContainer: {
    padding: 16,
    backgroundColor: 'white',
    borderRadius: 8,
  },
  barcodeModalView: {
    width: '100%',
    maxWidth: 360,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 12,
    alignItems: 'stretch',
  },
  barcodeTitle: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'center',
  },
  barcodeValue: {
    marginTop: 8,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  barcodeValueCompact: {
    marginTop: 6,
    fontSize: 14,
  },
  barcodeHelperText: {
    marginTop: 8,
    fontSize: 11,
    lineHeight: 15,
    textAlign: 'center',
  },
  barcodePreviewShell: {
    width: '100%',
    minHeight: 128,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  barcodePreviewSvg: {
    maxWidth: '100%',
    alignSelf: 'center',
  },
  themeOption: {
    flexBasis: '31%',
    minWidth: 108,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  themeOptionActive: {
    borderWidth: 2,
  },
  themeOptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  themeSwatches: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  themeSwatch: {
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 1,
  },
  backupModal: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
  },
  modalForm: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  formSection: {
    marginTop: 12,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  formRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  formField: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginTop: 0,
  },
  officeScanBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.48)',
    paddingHorizontal: 12,
  },
  officeScanModal: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 12,
    overflow: 'hidden',
  },
  officeScanEmpty: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  officeScanCameraShell: {
    width: '100%',
    aspectRatio: 3 / 4,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
  },
  officeScanCamera: {
    ...StyleSheet.absoluteFillObject,
  },
  officeScanOverlay: {
    ...StyleSheet.absoluteFillObject,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  officeScanFrame: {
    width: '82%',
    aspectRatio: 1.5,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.85)',
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.12)',
  },
  officeScanFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 99,
  },
  typeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 8,
  },
  itemMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 6,
  },
  itemActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  tinyBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  previewModal: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  barcodeFrame: {
    width: '100%',
    height: 200,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  barcodeCaption: {
    marginTop: 12,
    fontSize: 12,
    textAlign: 'center',
  },
  barcodePreviewFallback: {
    width: '100%',
    minHeight: 88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  barcodeSheetBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.34)',
    paddingHorizontal: 12,
    paddingVertical: 20,
  },
  barcodeSheet: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 12,
    overflow: 'hidden',
  },
  barcodeSheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.45)',
    marginBottom: 2,
  },
  barcodeSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  barcodeSheetHeaderText: {
    flex: 1,
    gap: 3,
  },
  barcodeSheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  barcodeSheetMeta: {
    fontSize: 12,
    lineHeight: 16,
  },
  barcodeSheetCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  barcodeSheetBody: {
    gap: 10,
    paddingHorizontal: 2,
  },
  barcodeRawValue: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  barcodeSheetNote: {
    fontSize: 11,
    lineHeight: 15,
    textAlign: 'center',
  },
  historyLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  historyMetaLine: {
    fontSize: 12,
    marginTop: 2,
    lineHeight: 16,
  },
  moreSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  moreSheet: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    gap: 12,
    overflow: 'hidden',
  },
  moreSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  moreSheetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 2,
  },
  pickerModal: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    alignItems: 'stretch',
    overflow: 'hidden',
    maxHeight: '82%',
  },
  pickerBox: {
    marginTop: 8,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerFooter: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    paddingBottom: 2,
  },
  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 92,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
  },
  disabledBtn: {
    opacity: 0.5,
  },
  scanNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  scanNoticeSuccess: {
    backgroundColor: 'rgba(34, 197, 94, 0.95)',
  },
  scanNoticeDuplicate: {
    backgroundColor: 'rgba(245, 158, 11, 0.95)',
  },
  scanNoticeError: {
    backgroundColor: 'rgba(220, 38, 38, 0.95)',
  },
  scanNoticeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  laser: {
    position: 'absolute',
    left: '5%',
    right: '5%',
    height: 2,
    backgroundColor: '#ff3333',
    borderRadius: 2,
    shadowColor: '#ff3333',
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 4,
  },
  viewfinderContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  viewfinderTop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  viewfinderMiddle: {
    height: '30%',
    flexDirection: 'row',
  },
  viewfinderSide: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  viewfinderCenter: {
    width: '80%',
    borderColor: 'rgba(255,255,255,0.7)',
    borderWidth: 2,
    borderRadius: 16,
  },
  viewfinderBottom: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 24,
  },
  viewfinderText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
});

export type MainAppStyles = typeof mainAppStyles;
